"""
Invite service (Phase 5) — the human-collaboration piece.

Owns the lifecycle of `invites` collection rows beyond raw CRUD:
  • Issue an invite + send a branded email.
  • Auto-issue when a task is assigned to an email that has no account.
  • Accept-on-signup: when a new user signs up with an invited email, all
    pending invites for that email are accepted atomically — they're added
    to the right orgs/projects with the right roles, and any tasks that
    were `assigned_to_email = "their@email"` are swapped to
    `assigned_to = <new_user_id>` and `assignee_kind = "user"`.

Tokens: the URL-safe random token generated by `invite_repository.create`
is the public credential.  We also expose `make_invite_jwt` for clients
that want a signed JWT-style token (lookup is identical — the repo stores
the literal string and `get_by_token` matches it).
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional

import structlog
from bson import ObjectId

from backend.core.config import settings
from backend.db.mongodb.models.invite import (
    Invite,
    InviteCreate,
    InviteRole,
    InviteScope,
    InviteStatus,
)
from backend.db.mongodb.repositories.invite_repository import invite_repository
from backend.db.mongodb.repositories.task_repository import task_repository
from backend.services.notification_service import notification_service

logger = structlog.get_logger(__name__)


def _frontend_base() -> str:
    base = (
        getattr(settings, "PRODUCTION_DOMAIN", None)
        or getattr(settings, "FRONTEND_URL", None)
        or "https://lumicoria.ai"
    )
    return str(base).rstrip("/")


def _accept_url(token: str) -> str:
    """Public-facing accept page on the frontend."""
    return f"{_frontend_base()}/invites/accept?token={token}"


def _logo_url() -> Optional[str]:
    """Absolute URL the email client uses to fetch the brand mark.

    Email clients cannot fetch `localhost` URLs (and many block private
    domains entirely), so we suppress the URL in development.  The email
    template renders a CSS-only brand tile with a centred "L" letterform as
    the fallback — visually identical to the real mark and 100% reliable.

    Production: set `EMAIL_BRAND_LOGO_URL` (or `BRAND_LOGO_URL`) in env to a
    publicly-reachable HTTPS URL.  We also accept `PRODUCTION_DOMAIN` —
    when that's set we assume the static asset is served from there.
    """
    # Explicit override always wins.
    explicit = (
        getattr(settings, "EMAIL_BRAND_LOGO_URL", None)
        or getattr(settings, "BRAND_LOGO_URL", None)
    )
    if explicit:
        return str(explicit)

    # If a real production domain is configured, build from it.
    prod = getattr(settings, "PRODUCTION_DOMAIN", None)
    if prod:
        base = str(prod).rstrip("/")
        if base.startswith("http"):
            return f"{base}/images/lumicoria-logo-primary.png"

    # Otherwise return None so the CSS fallback (the "L" tile) renders.
    return None


def _wordmark_url() -> Optional[str]:
    """Optional brand wordmark — for the email header.  Falls back to None
    when not configured."""
    custom = getattr(settings, "BRAND_WORDMARK_URL", None)
    if custom:
        return str(custom)
    return None


def _fmt_due_label(due: Optional[datetime]) -> str:
    if not due:
        return "No due date"
    now = datetime.utcnow()
    delta = due - now
    if delta.total_seconds() < 0:
        return f"Overdue (was {due.strftime('%a, %b %d')})"
    days = int(delta.total_seconds() / 86_400)
    if days < 1:
        return f"Due today, {due.strftime('%H:%M')}"
    if days == 1:
        return f"Due tomorrow, {due.strftime('%H:%M')}"
    if days < 7:
        return f"Due {due.strftime('%a, %b %d')}"
    return due.strftime('%a, %b %d %Y')


async def _resolve_inviter_snapshot(inviter_user_id: str) -> Dict[str, Optional[str]]:
    """Look up the inviter's display name + email for the invite snapshot."""
    try:
        from backend.db.mongodb.mongodb import MongoDB
        col = await MongoDB.get_collection("users")
        try:
            uid: Any = ObjectId(inviter_user_id)
        except Exception:
            uid = inviter_user_id
        doc = await col.find_one({"_id": uid})
        if not doc:
            return {"name": None, "email": None}
        return {
            "name": doc.get("full_name") or (doc.get("email") or "").split("@")[0],
            "email": doc.get("email"),
        }
    except Exception:
        return {"name": None, "email": None}


async def _resolve_org_name(org_id: Optional[str]) -> Optional[str]:
    if not org_id:
        return None
    try:
        from backend.db.mongodb.mongodb import MongoDB
        col = await MongoDB.get_collection("organizations")
        try:
            oid: Any = ObjectId(org_id)
        except Exception:
            oid = org_id
        doc = await col.find_one({"_id": oid})
        if doc:
            return doc.get("name")
    except Exception:
        pass
    return None


async def _resolve_project_name(project_id: Optional[str]) -> Optional[str]:
    if not project_id:
        return None
    try:
        from backend.db.mongodb.mongodb import MongoDB
        col = await MongoDB.get_collection("lumicoria_projects")
        try:
            pid: Any = ObjectId(project_id)
        except Exception:
            pid = project_id
        doc = await col.find_one({"_id": pid})
        if doc:
            return doc.get("title") or doc.get("name")
    except Exception:
        pass
    return None


async def _resolve_tasks(task_ids: List[str]) -> List[Dict[str, Any]]:
    """Hydrate task IDs into [{title, due_label}, ...] for the email."""
    rows: List[Dict[str, Any]] = []
    if not task_ids:
        return rows
    try:
        from backend.db.mongodb.mongodb import MongoDB
        col = await MongoDB.get_collection("tasks")
        oids: List[ObjectId] = []
        for tid in task_ids:
            try:
                oids.append(ObjectId(str(tid)))
            except Exception:
                continue
        if not oids:
            return rows
        async for d in col.find({"_id": {"$in": oids}}, projection={"title": 1, "due_date": 1, "priority": 1}):
            rows.append({
                "title": d.get("title") or "Untitled task",
                "due_label": _fmt_due_label(d.get("due_date")),
                "priority": (d.get("priority") or "medium"),
            })
    except Exception as e:
        logger.debug("invite_service: task hydrate failed", error=str(e))
    return rows


# ── Public surface ──────────────────────────────────────────────────────


class InviteService:
    """Application-level invite operations."""

    async def issue_invite(
        self,
        *,
        payload: InviteCreate,
        invited_by: str,
        send_email: bool = True,
    ) -> Invite:
        """Create the invite row + send the email.  Idempotent — if a pending
        invite already exists for the same scope/email, the repo returns it
        and we resend the email (no duplicate row)."""
        inviter = await _resolve_inviter_snapshot(invited_by)
        invite = await invite_repository.create(
            payload=payload,
            invited_by=invited_by,
            inviter_name=inviter["name"],
            inviter_email=inviter["email"],
        )

        if send_email:
            try:
                await self.send_invite_email(invite=invite)
            except Exception as e:
                logger.warning("invite_email_failed", invite_id=str(invite.id), error=str(e))

        return invite

    async def send_invite_email(self, *, invite: Invite) -> bool:
        """Render and send the task_invite.html email."""
        if not invite or not invite.email:
            return False

        org_name = await _resolve_org_name(str(invite.organization_id) if invite.organization_id else None)
        project_name = await _resolve_project_name(str(invite.project_id) if invite.project_id else None)
        tasks = await _resolve_tasks([str(t) for t in (invite.task_ids or [])])

        scope_label = "organization"
        if invite.scope == InviteScope.PROJECT:
            scope_label = "project"
        elif invite.scope == InviteScope.TASK:
            scope_label = "task"

        inviter_name = invite.inviter_name or "A Lumicoria user"
        subject = f"{inviter_name} invited you to Lumicoria"

        # Mark the reminder timestamp + bump counter for visibility.
        try:
            await invite_repository.mark_reminder_sent(str(invite.id))
        except Exception:
            pass

        ok = await notification_service.send_email_notification(
            to_email=invite.email,
            template_name="task_invite",
            template_data={
                "subject": subject,
                "inviter_name": inviter_name,
                "inviter_email": invite.inviter_email,
                "recipient_email": invite.email,
                "role": invite.role.value if hasattr(invite.role, "value") else str(invite.role),
                "scope": scope_label,
                "organization_name": org_name,
                "project_name": project_name,
                "tasks": tasks,
                "task_count": len(tasks),
                "message": invite.message,
                "accept_url": _accept_url(invite.token),
                "logo_url": _logo_url(),
                "wordmark_url": _wordmark_url(),
                "expires_at": invite.expires_at.strftime("%b %d, %Y") if invite.expires_at else None,
            },
        )
        return bool(ok)

    async def revoke_invite(self, invite_id: str, *, requested_by: str) -> bool:
        """Owner check before revoking."""
        invite = await invite_repository.get_by_id(invite_id)
        if not invite:
            return False
        if str(invite.invited_by) != str(requested_by):
            return False
        return await invite_repository.mark_revoked(invite_id)

    async def resend_invite(self, invite_id: str, *, requested_by: str) -> bool:
        invite = await invite_repository.get_by_id(invite_id)
        if not invite or str(invite.invited_by) != str(requested_by):
            return False
        if invite.status != InviteStatus.PENDING:
            return False
        return await self.send_invite_email(invite=invite)

    # ── Accept-on-signup hook ───────────────────────────────────────────

    async def accept_pending_invites_for_user(
        self,
        *,
        user_id: str,
        email: str,
    ) -> Dict[str, Any]:
        """Called from auth/signup after the user row is created.

        For every PENDING invite for this email:
          • Mark accepted.
          • Add the user to the linked organization with the right role.
          • Add the user to the linked project (when applicable).
          • Re-assign linked tasks from `assigned_to_email` to `assigned_to: user_id`.
        Returns a summary so the caller can include it in the response.
        """
        pending = await invite_repository.find_pending_by_email(email)
        if not pending:
            return {"accepted": 0, "orgs_joined": 0, "tasks_reassigned": 0}

        orgs_joined = 0
        tasks_reassigned = 0
        accepted_ids: List[str] = []

        for invite in pending:
            try:
                # 1. Accept (atomic — Mongo find_one_and_update keyed by status=pending)
                accepted = await invite_repository.mark_accepted(str(invite.id), user_id)
                if not accepted:
                    continue
                accepted_ids.append(str(invite.id))

                # 2. Add to org with the right role.  Plan caps gate seat
                #    consumption: a Team plan with 3 seats blocks the 4th invite.
                org_id = str(invite.organization_id) if invite.organization_id else None
                if org_id:
                    try:
                        from backend.db.mongodb.repositories.organization_repository import (
                            organization_repository,
                        )
                        from backend.services.billing.plan_caps import (
                            PlanCapExceeded,
                            assert_can_add_seat,
                        )
                        try:
                            await assert_can_add_seat(org_id)
                        except PlanCapExceeded as cap_exc:
                            logger.warning(
                                "invite_accept: seat cap exceeded",
                                invite_id=str(invite.id),
                                detail=cap_exc.detail,
                            )
                            # Don't rollback the invite — the seat shortfall is
                            # an admin problem.  Surface a structured error so
                            # the caller can render the upsell.
                            raise

                        role = invite.role.value if hasattr(invite.role, "value") else str(invite.role)
                        await organization_repository.add_member(
                            organization_id=org_id,
                            user_id=user_id,
                            is_admin=(role == InviteRole.ADMIN.value),
                        )
                        orgs_joined += 1
                        # Mirror into seat_assignments so seats_used reflects reality.
                        try:
                            from backend.db.mongodb.repositories.org_subscription_repository import (
                                seat_assignment_repository,
                            )
                            await seat_assignment_repository.assign(
                                org_id, user_id, assigned_by=str(invite.invited_by) if invite.invited_by else None,
                            )
                        except Exception:
                            pass
                    except Exception as e:
                        logger.warning("invite_accept: org add_member failed",
                                       invite_id=str(invite.id), error=str(e))

                # 3. Re-assign linked tasks
                if invite.task_ids:
                    try:
                        for tid in invite.task_ids:
                            tid_str = str(tid)
                            await task_repository.update_task(
                                task_id=tid_str,
                                organization_id=org_id or user_id,
                                update_data={
                                    "assigned_to": user_id,
                                    "assigned_to_email": None,
                                    "assignee_kind": "user",
                                    "invite_id": str(invite.id),
                                },
                            )
                            tasks_reassigned += 1
                    except Exception as e:
                        logger.warning("invite_accept: task reassignment failed",
                                       invite_id=str(invite.id), error=str(e))

            except Exception as e:
                logger.warning("invite_accept: invite failed",
                               invite_id=str(invite.id), error=str(e))

        return {
            "accepted": len(accepted_ids),
            "orgs_joined": orgs_joined,
            "tasks_reassigned": tasks_reassigned,
            "invite_ids": accepted_ids,
        }

    # ── Auto-invite from task assignment ────────────────────────────────

    async def assign_task_by_email_or_invite(
        self,
        *,
        task_id: str,
        email: str,
        organization_id: str,
        invited_by: str,
        role: InviteRole = InviteRole.MEMBER,
    ) -> Dict[str, Any]:
        """Phase 5: assign a task to an email address.

        If the email belongs to an existing user, we do a normal assignment.
        If not, we tag the task with `assigned_to_email`, set `assignee_kind="email_invite"`,
        and issue an invite that includes this task in `task_ids`.  Returns a
        summary the API can hand straight back to the frontend.
        """
        email_norm = (email or "").strip().lower()
        if not email_norm:
            raise ValueError("Email is required for invite-based assignment")

        # Existing user?
        from backend.db.mongodb.repositories.user_repository import get_user_repository
        user_repo = await get_user_repository()
        existing_user = await user_repo.get_user_by_email(email_norm)

        if existing_user:
            user_id = str(existing_user.id)
            await task_repository.update_task(
                task_id=task_id,
                organization_id=organization_id,
                update_data={
                    "assigned_to": user_id,
                    "assigned_to_email": None,
                    "assignee_kind": "user",
                },
            )
            return {
                "assigned": True,
                "via": "existing_user",
                "user_id": user_id,
                "invite_id": None,
            }

        # No existing user — issue invite + stamp task.
        invite = await self.issue_invite(
            payload=InviteCreate(
                email=email_norm,
                scope=InviteScope.TASK,
                organization_id=organization_id,
                task_ids=[task_id],
                role=role,
                expires_in_days=14,
            ),
            invited_by=invited_by,
        )

        await task_repository.update_task(
            task_id=task_id,
            organization_id=organization_id,
            update_data={
                "assigned_to": None,
                "assigned_to_email": email_norm,
                "assignee_kind": "email_invite",
                "invite_id": str(invite.id),
            },
        )
        return {
            "assigned": True,
            "via": "invite",
            "user_id": None,
            "invite_id": str(invite.id),
            "invite_token": invite.token,
            "invite_expires_at": invite.expires_at.isoformat() + "Z" if invite.expires_at else None,
        }


invite_service = InviteService()
